// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsxrhvasefepzumnixku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeHJodmFzZWZlcHp1bW5peGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTIyNDQsImV4cCI6MjA3Mzc4ODI0NH0.RHl4EM7LiP6pfvT4RQvsamzqCnPqShFqfGdGXTyrYrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});